#!/usr/bin/env python3
"""
assemble_manuscript.py — concatenate the section files into one draft.

The sections are written and reviewed separately, in writing order, but a draft
has to be read in reading order and sent as one file. This does that and nothing
else: no reformatting, no renumbering, no reflowing. Each section file remains
the single source of truth for its own text.

Usage:
    python3 scripts/assemble_manuscript.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "paper" / "manuscript"
OUT = SRC / "PAPER.md"

# reading order, which is not the writing order recorded in README.md
ORDER = ["abstract.md", "intro.md", "related.md", "method.md", "results.md",
         "taxonomy.md", "threats.md", "discussion.md"]

HEADER = """<!-- GENERATED by scripts/assemble_manuscript.py from the section
     files in this directory, in reading order. Do not edit this file: edit the
     section it came from and re-run the script. -->

# Traceability and estimate coverage as corpus-eligibility constraints

**Malek Khannoussi** · independent researcher · khannoussimalek@gmail.com

Draft. Target venue MSR, technical track. Every number is traced to a script and
a commit in `paper/numbers.md`; `PROVENANCE_CHECK.md` in this directory is the
audit. Tables referenced as Table 1 and Table 2 are
`paper/table1_eligibility.md` and `paper/table2_visibility.md`.

---
"""


def main():
    parts = [HEADER]
    for name in ORDER:
        f = SRC / name
        if not f.exists():
            raise SystemExit(f"missing section: {f}")
        parts.append(f.read_text().rstrip() + "\n")
    OUT.write_text("\n---\n\n".join(parts))
    n = sum(len(p.split()) for p in parts)
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(ORDER)} sections, ~{n:,} words")


if __name__ == "__main__":
    main()
