#!/usr/bin/env python3
"""
check_provenance.py -- enforce R7: every number in the manuscript exists in
paper/numbers.md, and emit paper/manuscript/PROVENANCE_CHECK.md.

R7 is the rule that keeps this paper honest: a number without a script and a
commit behind it does not go in. Checking that by hand does not survive a second
draft, so it is mechanical here and re-runnable.

WHAT TOKEN MATCHING CAN AND CANNOT PROVE. An earlier version of this script
reported "zero unsourced" over every numeric token, which was a false pass: in a
document as number-dense as numbers.md, a two-digit token like `12` or `27`
matches *something* by coincidence, so its presence is not evidence of
provenance. Tokens are therefore split:

  STRICT  -- distinctive: >=3 significant digits, or carrying a thousands
             separator, decimal point, or percent sign. A literal match in
             numbers.md is real evidence for these, and a miss is a real failure.
             These are what the pass/fail verdict is computed over.

  WEAK    -- bare one- or two-digit integers, and calendar years. Literal
             matching proves nothing here, so they are NOT counted as verified.
             They are listed in the report for the reader's eye instead, with the
             files they appear in.

Reporting a strict verdict and an explicit weak list is the honest version. A
single "zero unsourced" number over both classes would overstate the check.

Exit 1 if any STRICT token is unsourced, so this can gate a submission.

Usage:
    python3 scripts/check_provenance.py            # write the report
    python3 scripts/check_provenance.py --quiet    # exit code only
"""
import argparse
import collections
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANUSCRIPT = ROOT / "paper" / "manuscript"
NUMBERS = ROOT / "paper" / "numbers.md"
OUT = MANUSCRIPT / "PROVENANCE_CHECK.md"

TOKEN = re.compile(r"\d[\d,]*(?:\.\d+)?%?")
# Dates first, or "2026-05-24" contributes bogus "05" and "24" tokens.
DATEISH = re.compile(r"\d{4}-\d{2}(?:-\d{2})?")
YEAR = re.compile(r"^(19|20)\d{2}$")

# Tokens that look numeric but are not measurements. Explicit so that every
# exclusion is visible: a silent filter here would defeat the whole check.
NOT_MEASUREMENTS = {
    # section cross-references
    "2.1", "2.2", "2.3", "2.4", "2.5", "4.1", "4.2", "4.3", "4.4", "4.5",
    "5.1", "5.2", "5.3", "5.4", "6.1", "6.2", "6.3", "6.4", "6.5", "6.6",
    "6.7", "6.8",
    # DOI / arXiv / dataset identifiers
    "104005", "1804.02433", "2404.01950", "2501.15387", "2605.16133",
    "15719919",
    # upstream issue, PR and branch identifiers, and one commit hash in prose
    "1124", "998", "1471779", "256", "5179907",
    # detector version 3.1.4 tokenises as "3.1"
    "3.1",
}


def numbers_sections():
    """-> [(label, body)] for paper/numbers.md, in document order."""
    text = NUMBERS.read_text()
    parts = re.split(r"^#{2,3} +(.*)$", text, flags=re.M)
    out = [("preamble", parts[0])]
    for i in range(1, len(parts), 2):
        label = parts[i].strip()
        # "1d. The key matcher is ..." -> "§1d"; otherwise keep it short
        m = re.match(r"([0-9]+[a-z]?)\.\s*(.*)", label)
        short = f"§{m.group(1)}" if m else label.split("—")[0].strip()[:38]
        out.append((short, parts[i + 1]))
    return out


def classify(tok):
    """-> 'strict' | 'weak' | None (drop)."""
    if tok in NOT_MEASUREMENTS:
        return None
    if YEAR.match(tok):
        return "weak"
    digits = tok.strip("%").replace(",", "").replace(".", "")
    if len(digits) < 2:
        return None                              # single digits are prose
    distinctive = ("," in tok or "." in tok or "%" in tok or len(digits) >= 3)
    return "strict" if distinctive else "weak"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args()

    sections = numbers_sections()

    strict = collections.defaultdict(set)
    weak = collections.defaultdict(set)
    for f in sorted(MANUSCRIPT.glob("*.md")):
        if f.name == OUT.name:
            continue
        text = DATEISH.sub(" ", f.read_text())
        for raw in TOKEN.findall(text):
            tok = raw.rstrip(".,")
            kind = classify(tok)
            if kind == "strict":
                strict[tok].add(f.name)
            elif kind == "weak":
                weak[tok].add(f.name)

    sourced, unsourced = {}, {}
    for tok, files in strict.items():
        hits = [label for label, body in sections if tok in body]
        (sourced if hits else unsourced)[tok] = (files, hits)

    L = []
    add = L.append
    add("# Provenance check — every number in the manuscript")
    add("")
    add("<!-- GENERATED by scripts/check_provenance.py. Do not edit by hand. -->")
    add("")

    if unsourced:
        add(f"## ❌ {len(unsourced)} unsourced — fix before submission")
        add("")
        add("| number | appears in |")
        add("|---|---|")
        for tok in sorted(unsourced):
            add(f"| `{tok}` | {', '.join(sorted(unsourced[tok][0]))} |")
    else:
        add(f"## ✅ Zero unsourced distinctive quantities")
        add("")
        add(f"All **{len(sourced)}** distinctive numeric quantities in "
            "`paper/manuscript/` resolve to a section of `paper/numbers.md`, and "
            "every such section names the script or artifact and the commit it "
            "was last changed in. **R7 holds for every number token matching can "
            "verify.**")
    add("")
    add("**What this verdict covers, and what it does not.** A literal match is "
        "evidence only for a *distinctive* token — one with three or more "
        "significant digits, or a thousands separator, decimal point or percent "
        "sign. In a document as number-dense as `numbers.md`, a bare two-digit "
        f"integer matches something by coincidence, so the {len(weak)} short "
        "integers and calendar years listed at the end are **not** counted as "
        "verified. They are listed for the reader instead. An earlier version of "
        "this script counted both classes together and reported a pass it had not "
        "established.")
    add("")

    add("## The 1,822 rule")
    add("")
    add("`1,822` is the published project count that is **not reproducible** and "
        "must never be quoted beside a per-project number. It travels only with "
        "`1,276` (final-state, key-based) and `2,506` (name-union, the dataset's "
        "own method). Checked per paragraph, not per line:")
    add("")
    hits = 0
    for f in sorted(MANUSCRIPT.glob("*.md")):
        if f.name == OUT.name:
            continue
        for n, para in enumerate(f.read_text().split("\n\n"), 1):
            if "1,822" not in para:
                continue
            hits += 1
            ok = "1,276" in para and "2,506" in para
            add(f"* `{f.name}` paragraph {n} — "
                + ("✅ travels with both 1,276 and 2,506"
                   if ok else "⚠️ **CHECK CONTEXT** — one of the two is missing"))
    if not hits:
        add("* absent from the manuscript")
    add("")

    add("## Distinctive quantities, their file, and the section that sources them")
    add("")
    add("Each `numbers.md` section names the script or artifact and its commit.")
    add("")
    add("| number | appears in | sourced by |")
    add("|---|---|---|")

    def sortkey(t):
        try:
            return (0, float(t.strip("%").replace(",", "")))
        except ValueError:
            return (1, 0.0)

    for tok in sorted(sourced, key=sortkey):
        files, hits_ = sourced[tok]
        add(f"| `{tok}` | {', '.join(sorted(files))} | {', '.join(hits_[:3])} |")
    add("")

    add(f"## Short integers and years — {len(weak)} tokens, listed not verified")
    add("")
    add("Token matching cannot establish provenance for these. Each is carried by "
        "a claim whose distinctive numbers are verified above — e.g. `12 of 38`, "
        "`3 of 96`, `n=28` — so the reader confirms them in context.")
    add("")
    add("| number | appears in |")
    add("|---|---|")
    for tok in sorted(weak, key=sortkey):
        add(f"| `{tok}` | {', '.join(sorted(weak[tok]))} |")
    add("")

    add("## Deliberate exclusions")
    add("")
    add("Numeric tokens dropped as not-measurements, listed so the filter is "
        "auditable rather than silent: section cross-references, DOI and arXiv "
        "identifiers, the Zenodo dataset id, upstream issue/PR/branch numbers, "
        "one commit hash quoted in prose, and the detector version. ISO dates are "
        "stripped before tokenising, so `2026-05-24` contributes no `05` or `24`.")
    add("")
    add("```")
    add(", ".join(sorted(NOT_MEASUREMENTS)))
    add("```")
    add("")
    add("Regenerate: `python3 scripts/check_provenance.py`")

    OUT.write_text("\n".join(L) + "\n")

    if not a.quiet:
        print(f"wrote {OUT.relative_to(ROOT)}")
        print(f"  strict: {len(sourced)} sourced, {len(unsourced)} unsourced")
        print(f"  weak (listed, not verified): {len(weak)}")
        for tok in sorted(unsourced):
            print(f"  UNSOURCED {tok}  ({', '.join(sorted(unsourced[tok][0]))})")
    return 1 if unsourced else 0


if __name__ == "__main__":
    sys.exit(main())
