#!/usr/bin/env python3
"""
make_table1.py -- emit paper/table1_eligibility.md from its two source JSONs.

Table 1 is the paper's central table and was hand-assembled markdown until now
(paper/numbers.md §7 flagged that as the highest-priority provenance gap). It is
generated here so it cannot drift from paper/traceability_probe.json and
paper/ticket_coverage.json.

Deterministic by construction: no clock, no randomness, explicit sort order, so
a second run is byte-identical to the first.

Rates are formatted from the ratio in ONE rounding step. Do not round to 4dp and
then to 1dp -- that double-rounding is what produced the spurious knox 84.3->84.4
and helix 10.5->10.4 discrepancies recorded in PROJECT_STATE.md §7.

R1: this script reads coverage and existence counts only. It never opens an
outcome artifact and has no code path that can produce a timing statistic.

Usage:
    python3 scripts/make_table1.py [--check]

    --check  regenerate in memory and diff against the committed file;
             exit 1 if they differ. Nothing is written.
"""
import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROBE = ROOT / "paper" / "traceability_probe.json"
COVERAGE = ROOT / "paper" / "ticket_coverage.json"
OUT = ROOT / "paper" / "table1_eligibility.md"

# Held out as of 2026-07-30 (PROJECT_STATE.md §3). Marked in the table so a
# reader cannot mistake a coverage row for permission to measure an outcome.
HELD_OUT = {"ozone", "tez", "zookeeper", "ranger", "oozie", "knox", "sqoop"}
QUARANTINED = {"hbase", "phoenix"}


def pct(numerator, denominator):
    """One rounding step, from the ratio. Never round twice."""
    if not denominator:
        raise ValueError("empty denominator -- refusing to emit a rate")
    return f"{100.0 * numerator / denominator:.1f}%"


def load():
    probe = json.loads(PROBE.read_text())
    coverage = json.loads(COVERAGE.read_text())
    by_project = {r["project"]: r for r in probe["projects"]}
    ticket = {r["project"]: r for r in coverage["projects"]}

    if len(by_project) != len(probe["projects"]):
        raise ValueError("duplicate project in traceability_probe.json")

    passing = sorted(
        (r for r in probe["projects"] if r["passes_bar"]),
        key=lambda r: (-r["rate_multi"], r["project"]),
    )
    dropped = sorted(
        (r for r in probe["projects"] if not r["passes_bar"]),
        key=lambda r: (-r["rate_multi"], r["project"]),
    )

    missing = [r["project"] for r in passing if r["project"] not in ticket]
    if missing:
        raise ValueError(f"passing projects absent from ticket_coverage: {missing}")

    return probe, passing, dropped, ticket


def marker(project):
    if project in HELD_OUT:
        return " †"
    if project in QUARANTINED:
        return " ‡"
    return ""


def render(probe, passing, dropped, ticket):
    bar = probe["bar"]
    n_probed = probe["n_probed"]
    lines = []
    add = lines.append

    add("# Table 1 — corpus eligibility, both traceability channels")
    add("")
    add("<!-- GENERATED by scripts/make_table1.py from")
    add("     paper/traceability_probe.json and paper/ticket_coverage.json.")
    add("     Do not edit by hand: re-run the script. -->")
    add("")
    add(f"**{len(passing)} of {n_probed} projects clear the pre-registered "
        f"{bar:.2f} commit-side bar. All {len(passing)} are Hadoop-ecosystem.**")
    add("")

    # --- passing -------------------------------------------------------------
    add(f"## Eligible ({len(passing)})")
    add("")
    add("| # | project | Jira key(s) | HEAD | commits scanned | single-key | "
        "multi-key | tickets total | tickets cited | **ticket-side** |")
    add("|---:|---|---|---|---:|---:|---:|---:|---:|---:|")
    for i, r in enumerate(passing, 1):
        p = r["project"]
        t = ticket[p]
        add("| {} | {}{} | `{}` | `{}` | {:,} | {} | **{}** | {:,} | {:,} | **{}** |".format(
            i,
            p,
            marker(p),
            r["keys_multi"],
            r["head_sha"][:10],
            r["commits_scanned"],
            pct(r["commits_citing_single"], r["commits_scanned"]),
            pct(r["commits_citing_multi"], r["commits_scanned"]),
            t["jira_tickets_total"],
            t["tickets_cited_by_a_commit"],
            pct(t["tickets_cited_by_a_commit"], t["jira_tickets_total"]),
        ))
    add("")
    add("† held-out corpus: coverage and existence counts only, no outcome ever "
        "observed (`PROJECT_STATE.md` §3).")
    add("‡ quarantined 2026-07-30, dropped from the held-out corpus; coverage "
        "retained, outcome inputs sequestered in `spent/` (`spent/README.md`).")
    add("")

    # --- dropped -------------------------------------------------------------
    add(f"## Dropped ({len(dropped)})")
    add("")
    add("| # | project | HEAD | commits | multi-key | drop reason (measured) |")
    add("|---:|---|---|---:|---:|---|")
    for i, r in enumerate(dropped, len(passing) + 1):
        add("| {} | {} | `{}` | {:,} | {} | `{}` |".format(
            i,
            r["project"],
            r["head_sha"][:10],
            r["commits_scanned"],
            pct(r["commits_citing_multi"], r["commits_scanned"]),
            r["drop_reason"],
        ))
    add("")

    # --- caption -------------------------------------------------------------
    kylin = next(r for r in passing if r["project"] == "kylin")
    kt = ticket["kylin"]
    lo = min(ticket[r["project"]]["ticket_side_rate"] for r in passing)
    hi = max(ticket[r["project"]]["ticket_side_rate"] for r in passing)
    lo_p = f"{100.0 * lo:.1f}%"
    hi_p = f"{100.0 * hi:.1f}%"
    ck_lo = min(r["rate_multi"] for r in passing)
    ck_hi = max(r["rate_multi"] for r in passing)

    add("## Caption")
    add("")
    add(
        "**The two traceability channels diverge, and the one the literature "
        "publishes is not the one an issue-linked study needs.** The commit-side "
        "rate — what fraction of commits cite a ticket — is what SEOSS 33 reports "
        "and what selection criteria use. The ticket-side rate — what fraction of "
        "tickets ever receive a citing commit — is what a ticket-anchored study "
        "depends on. "
        f"**Kylin cites a ticket in {pct(kylin['commits_citing_multi'], kylin['commits_scanned'])} "
        f"of its commits while only {pct(kt['tickets_cited_by_a_commit'], kt['jira_tickets_total'])} "
        "of its tickets are ever touched by one** — it clears the bar comfortably "
        "and leaves seven of every eight tickets with no commit at all. Across the "
        f"{len(passing)} eligible projects the commit-side rate runs "
        f"{100.0 * ck_lo:.1f}–{100.0 * ck_hi:.1f}% while the ticket-side rate runs "
        f"**{lo_p}–{hi_p}, with none above {hi_p}**."
    )
    add("")
    add(
        "**Truncation caveat, load-bearing.** Ticket-side coverage was computed "
        f"only for the {len(passing)} projects that had already cleared the "
        f"commit-side bar. The {lo_p}–{hi_p} range is therefore *within-passing "
        "variation* and licenses no claim about the "
        f"{len(dropped)} dropped projects, whose ticket-side rates were never "
        "measured, nor about any correlation between the two channels in general."
    )
    add("")
    add(
        "**Drop reasons are measured, not inferred.** The probe counts "
        "GitHub-issue references (`#NNN`, `GH-NNN`) alongside Jira keys, so "
        "`github_issue_references_dominate` means the GitHub count exceeds the "
        "Jira count in that repository. `below_bar_narrowly` (≥70%) and "
        "`low_commit_message_hygiene` are threshold labels on the measured rate."
    )
    add("")
    add(
        "**No timing column exists in this table and none may be added for a "
        "† row.** Every quantity above is a coverage or existence count, which is "
        "what the held-out rule permits (`PROJECT_STATE.md` §3)."
    )
    add("")
    add("Sources: `scripts/traceability_probe.py` → `paper/traceability_probe.json`; "
        "`scripts/ticket_coverage.py` → `paper/ticket_coverage.json`. "
        "Generated by `scripts/make_table1.py`.")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="diff against the committed file instead of writing")
    a = ap.parse_args()

    text = render(*load())

    if a.check:
        if not OUT.exists():
            print(f"{OUT} does not exist", file=sys.stderr)
            return 1
        if OUT.read_text() == text:
            print(f"{OUT.relative_to(ROOT)} is up to date ({len(text)} bytes)")
            return 0
        print(f"{OUT.relative_to(ROOT)} DIFFERS from a fresh render",
              file=sys.stderr)
        return 1

    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
